### ISSUE TITLE
Problems for visualizing attention map

### ISSUE THREAD

**Issue by jdyjjj** [damaggu/TADP#3]
Amazing work. May I ask where can I obtain the script for visualizing the attention map? Your reply would be very helpful to me.

**Comment by nkondapa** [comment]
Hi, in the demos folder there is a script `demo/cross_attention_visualization.sh`. This will give some args to run the python file `txt2img_ca_analysis.py`.
The visualization code makes use of a modified version of ldm (ldm_cross_attention).

**Comment by jdyjjj** [comment]
Thank you very much for your answer. I would also like to ask where I can download checkpoints. If I could receive your reply, it would be of great help to me.

**Comment by manuelknott** [comment]
Please refer to [download_data_and_checkpoints.sh](https://github.com/damaggu/TADP/blob/main/download_data_and_checkpoints.sh) Lines 7-11 for checkpoints.

**Comment by jdyjjj** [comment]
Thanks
