### ISSUE TITLE
Clarification on Testing VOC2012 Dataset with tadp_seg_blipmin40.ckpt

### ISSUE THREAD

**Issue by Yufei2000** [damaggu/TADP#5]
Thank you once again for your valuable work. I have an additional question regarding the testing process.

I noticed that the file tadp_seg_blipmin40.ckpt is mentioned as being used only for single-image inference. However, for whole dataset testing, the script test_tadp_mm.py seems to be primarily intended for the ADE20k and NYUv2 datasets. Could you please clarify if this script is also suitable for the VOC2012 dataset, or if there are any specific adjustments required for testing on VOC2012?

Your insights would be greatly appreciated.

Thank you for your continued support.

**Comment by nkondapa** [comment]
No the scripts are separated because we wrote a custom class in pytorch lightning for Pascal. You should use the commands in cvpr_experiments/pascal_segmentation.sh

**Comment by Yufei2000** [comment]
Thank you very much for your prompt and helpful reply! I greatly appreciate your assistance. I have a follow-up question regarding the checkpoint files:
Could you please clarify whether the **tadp_seg_blipmin40.ckpt** file is the checkpoint for the **ADE20k Semantic Segmentation task** or for the **VOC2012 dataset**? If it's not for VOC2012, is there a specific training checkpoint available for the VOC2012 dataset?
Your insights on this matter would be immensely helpful for my research. Thank you in advance for your time and expertise.
